---
title: "part2_main"
output: word_document
date: "2023-10-14"
---
##Computing the nonzero-interval.
```{r}
## Distribution, I have chosen for PART II, the beta distribution.
nonzero.interval <- function(a,b) { 
  c(a,b) 
}

```

##Computing the density 


```{r}
## gamma() in R computes the gamma function 

density <- function(x,a,b) {
  #Here, you can intialise the values for alpha and beta.
  alpha = 1
  beta = 1
  
  ifelse(a <= x & x <= b,gamma(alpha+beta)*x^(alpha-1)*(1-x)^(beta-1)/(gamma(alpha)*gamma(beta)), 0)
}

f<- Vectorize(density)

```

#Computing the distribution


```{r}
## Computing the cdf of the beta distribution 
distribution <- function(x,a,b) {
  ifelse(x<a,0, ifelse(x<=b,integrate(f,lower = a, upper = b),1))
}

```


#Expected value

```{r}
expected_value <- function(x,a,b){
  integrate(function(x) {x*density(x,a,b)},lower=-Inf,upper=Inf)$value
  
}

#alpha/(alpha+beta)

```


#Variance

```{r}
variance <- function(a,b){
  ev <- expected.value(a,b)
  integrate(function(x) {(x-ev)^2*density(x,a,b)},lower=-Inf,upper=Inf)$value
}
#(alpha*beta)/((alpha+beta)^2*(alpha+beta+1))

```



#HERE, I GENERATE THE FUNCTIONS FROM THE BETA DISTRIBUTION

```{r}
# Now I can generate random numbers using the generate function.
generate(1000,0.5,0.6)
generate(1000, 1, 1) 

```

```{r}

#quantile function
quantile <- Vectorize(function(p,a,b) {
  interval <- nonzero.interval(a,b)
  objective <- function(x) {(distribution(x,a,b) - p)^2 }
  optimise(objective, interval=c(interval[1], interval[2]))$minimum
})

#generate function
generate <- function(n,a,b) {
  beta <- rbeta(n,a,b) 
  quantile(beta,a,b)
}

```





