---
title: "GotmyRprogramback"
output: word_document
date: "2023-11-02"
---

#Question 1.
#Using R as a calculator 
```{r}
3 + 2*4
2^2 + 3

```

#Question 2

```{r}
sqrt(16)
exp(3)

```

#Question 3

#Use the ? to understand what log does
```{r}
?log
```

#Question 4
```{r}
exp(5) + sqrt(3*15^2 + log(9,base = 5))
```
#Question 5
```{r}
answer <- log(2,base=10)
answer
round(answer)
round(answer,digits=1)
floor(answer)
ceiling(answer)

```
#Question 6. Create a vector called numbers containing the numbers 15,20,25,30,....,105
```{r}
numbers <- seq(15,105,by=5)
numbers
```


#Question 7. Compute the length of numbers vector
```{r}
length(numbers)
```
#Question 8. 
```{r}
x <- 1:10
y <- 2* x
y
x^2
sqrt ( x )
sqrt ( x^2)
x + y
x * y
x + log ( y + 2)
```

#Scripts
#12
```{r}
x <- 1:50
y <- 2* x
y
x^2
sqrt ( x )
sqrt ( x^2)
x + y
x * y
x + log ( y + 2)
```
#Defining functions in R
#13
```{r}
hypotenuse <- function (x , y ) { sqrt ( x^2+ y^2) }
hypotenuse (3 ,4)
#[1] 5
hypotenuse (4 ,5)
#[1] 6.403124
hypotenuse (5 ,6)
#[1] 7.81025

```

#14

```{r}
distance.between.points <- function ( x1 , y1 , x2 , y2 ) {
x.new <- x1 - x2
y.new <- y1 - y2
hypotenuse ( x.new , y.new )
}

distance.between.points(1 ,1 ,3 ,4)
#[1] 3.605551
distance.between.points(3 ,4 ,3 ,4)
#[1] 0


```

#15. Celsius to degrees Fahrenheit

```{r}
to.fahrenheit <- function (C) {
  9*C/5 + 32
}
to.fahrenheit(0)
to.fahrenheit(100)



```

#16. Quadratic formula for finding the roots to the quadratic ax^2 + bx + c

```{r}
quadratic<- function (a,b,c) {
  (-b + c(-1,1)*sqrt(b^2-4*a*c))/2*a
}
quadratic(1,-1,-2)


```